name: Issues (Script Injection Example)
'on':
  issues:
    types:
      - opened
jobs:
  issues-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - env: #added
          issue_title: '${{ github.event.issue.title }}' #added
        run: |
          if [[ "$issue_title" == *"bug"* ]]; then
            echo "Issue is about a bug!"
          else
            echo "Issue is not about a bug"
          fi
